name: Vinted Bot   # nazwa workflowa

on:
  schedule:
    - cron: "*/5 * * * *"   # odpala się co 5 minut
  workflow_dispatch:        # pozwala też odpalić ręcznie

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install requests

      - name: Run bot
        run: python bot.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
